stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

before_script:
  - chmod +x gradlew
  - export GRADLE_USER_HOME='pwd'/.gradle
  
build-job:       # This job runs in the build stage, which runs first.
  image: gradle:8.0
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar

unit-test-job:   # This job runs in the test stage.
  image: gradle:8.0
  stage: test    # It only starts when the job in the build stage completes successfully.
  variables:
    DOWNLOAD_NAME: "calculator-app-test-coverage"
  script:
    - ./gradlew test
  artifacts:
    paths: 
      - build/reports/tests/test/index.html
    name: "'$DOWNLOAD_NAME'"

deploy-job:
  stage: deploy
  image: docker
  services:
    - docker:dind
  script:
    - echo $DOCKERHUB_USERNAME
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN 
    - docker build -t $DOCKERHUB_USERNAME/calculator .
    - docker push $DOCKERHUB_USERNAME/calculator



